# Generated by Django 6.1.1 on 2026-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brinquedos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='faixa_etaria',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
