# Generated by Django 6.1.1 on 2026-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brinquedos', '0003_seed_initial_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='categoria',
            field=models.CharField(choices=[('meninos', 'Meninos'), ('meninas', 'Meninas'), ('bebes', 'Bebês'), ('educacao', 'Educação'), ('jogos', 'Jogos'), ('ao_ar_livre', 'Ao ar livre'), ('criativos', 'Criativos')], default='criativos', max_length=20),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='imagem',
            field=models.CharField(blank=True, help_text='Caminho relativo em static/images, por exemplo: robo-roxo.png', max_length=100),
        ),
    ]
